### ISSUE TITLE
Create add organization modal

### ISSUE THREAD

**Issue by aprojas** [FundacionParaguaya/stoplight-mobile#1281]
Env: All
Users: Hub admins

## TASK

**Create add organization modal**

- [ ] Make description field optional and with restriction: 140 characters
- [ ] Remove add logo box from front-end and database
- [ ] Hide the information field but do not delete from database
